import type { ComponentType, SVGProps } from "react";
import {
  ArchiveBoxIcon as ArchiveBoxOutline,
  ArrowDownOnSquareIcon as ArrowDownOnSquareOutline,
  ArrowDownTrayIcon as ArrowDownTrayOutline,
  ArrowPathIcon as ArrowPathOutline,
  ArrowRightIcon as ArrowRightOutline,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleOutline,
  ArrowTrendingUpIcon as ArrowTrendingUpOutline,
  ArrowUpTrayIcon as ArrowUpTrayOutline,
  BanknotesIcon as BanknotesOutline,
  Bars3Icon as Bars3Outline,
  BellIcon as BellOutline,
  BookmarkIcon as BookmarkOutline,
  BriefcaseIcon as BriefcaseOutline,
  BuildingOffice2Icon as BuildingOffice2Outline,
  CalendarDaysIcon as CalendarDaysOutline,
  CalendarIcon as CalendarOutline,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightOutline,
  CheckCircleIcon as CheckCircleOutline,
  CheckIcon as CheckOutline,
  ChevronRightIcon as ChevronRightOutline,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckOutline,
  ClipboardDocumentIcon as ClipboardDocumentOutline,
  ClipboardDocumentListIcon as ClipboardDocumentListOutline,
  ClockIcon as ClockOutline,
  Cog6ToothIcon as Cog6ToothOutline,
  ComputerDesktopIcon as ComputerDesktopOutline,
  DevicePhoneMobileIcon as DevicePhoneMobileOutline,
  DeviceTabletIcon as DeviceTabletOutline,
  DocumentIcon as DocumentOutline,
  DocumentPlusIcon as DocumentPlusOutline,
  DocumentTextIcon as DocumentTextOutline,
  EnvelopeIcon as EnvelopeOutline,
  EnvelopeOpenIcon as EnvelopeOpenOutline,
  ExclamationCircleIcon as ExclamationCircleOutline,
  ExclamationTriangleIcon as ExclamationTriangleOutline,
  EyeIcon as EyeOutline,
  EyeSlashIcon as EyeSlashOutline,
  FlagIcon as FlagOutline,
  FolderIcon as FolderOutline,
  FolderOpenIcon as FolderOpenOutline,
  HandRaisedIcon as HandRaisedOutline,
  HomeIcon as HomeOutline,
  IdentificationIcon as IdentificationOutline,
  InboxIcon as InboxOutline,
  InformationCircleIcon as InformationCircleOutline,
  KeyIcon as KeyOutline,
  LifebuoyIcon as LifebuoyOutline,
  LinkIcon as LinkOutline,
  LockClosedIcon as LockClosedOutline,
  MagnifyingGlassIcon as MagnifyingGlassOutline,
  MapPinIcon as MapPinOutline,
  MoonIcon as MoonOutline,
  PaperAirplaneIcon as PaperAirplaneOutline,
  PencilSquareIcon as PencilSquareOutline,
  PhoneIcon as PhoneOutline,
  PlusCircleIcon as PlusCircleOutline,
  PlusIcon as PlusOutline,
  PrinterIcon as PrinterOutline,
  QuestionMarkCircleIcon as QuestionMarkCircleOutline,
  ShieldCheckIcon as ShieldCheckOutline,
  SparklesIcon as SparklesOutline,
  Squares2X2Icon as Squares2X2Outline,
  SunIcon as SunOutline,
  TrashIcon as TrashOutline,
  TrophyIcon as TrophyOutline,
  UserGroupIcon as UserGroupOutline,
  UserIcon as UserOutline,
  UserPlusIcon as UserPlusOutline,
  VideoCameraIcon as VideoCameraOutline,
  XMarkIcon as XMarkOutline,
} from "@heroicons/react/24/outline";
import {
  ArchiveBoxIcon as ArchiveBoxSolid,
  ArrowDownOnSquareIcon as ArrowDownOnSquareSolid,
  ArrowDownTrayIcon as ArrowDownTraySolid,
  ArrowPathIcon as ArrowPathSolid,
  ArrowRightIcon as ArrowRightSolid,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpSolid,
  ArrowUpTrayIcon as ArrowUpTraySolid,
  BanknotesIcon as BanknotesSolid,
  Bars3Icon as Bars3Solid,
  BellIcon as BellSolid,
  BookmarkIcon as BookmarkSolid,
  BriefcaseIcon as BriefcaseSolid,
  BuildingOffice2Icon as BuildingOffice2Solid,
  CalendarDaysIcon as CalendarDaysSolid,
  CalendarIcon as CalendarSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightSolid,
  CheckCircleIcon as CheckCircleSolid,
  CheckIcon as CheckSolid,
  ChevronRightIcon as ChevronRightSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckSolid,
  ClipboardDocumentIcon as ClipboardDocumentSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListSolid,
  ClockIcon as ClockSolid,
  Cog6ToothIcon as Cog6ToothSolid,
  ComputerDesktopIcon as ComputerDesktopSolid,
  DevicePhoneMobileIcon as DevicePhoneMobileSolid,
  DeviceTabletIcon as DeviceTabletSolid,
  DocumentIcon as DocumentSolid,
  DocumentPlusIcon as DocumentPlusSolid,
  DocumentTextIcon as DocumentTextSolid,
  EnvelopeIcon as EnvelopeSolid,
  EnvelopeOpenIcon as EnvelopeOpenSolid,
  ExclamationCircleIcon as ExclamationCircleSolid,
  ExclamationTriangleIcon as ExclamationTriangleSolid,
  EyeIcon as EyeSolid,
  EyeSlashIcon as EyeSlashSolid,
  FlagIcon as FlagSolid,
  FolderIcon as FolderSolid,
  FolderOpenIcon as FolderOpenSolid,
  HandRaisedIcon as HandRaisedSolid,
  HomeIcon as HomeSolid,
  IdentificationIcon as IdentificationSolid,
  InboxIcon as InboxSolid,
  InformationCircleIcon as InformationCircleSolid,
  KeyIcon as KeySolid,
  LifebuoyIcon as LifebuoySolid,
  LinkIcon as LinkSolid,
  LockClosedIcon as LockClosedSolid,
  MagnifyingGlassIcon as MagnifyingGlassSolid,
  MapPinIcon as MapPinSolid,
  MoonIcon as MoonSolid,
  PaperAirplaneIcon as PaperAirplaneSolid,
  PencilSquareIcon as PencilSquareSolid,
  PhoneIcon as PhoneSolid,
  PlusCircleIcon as PlusCircleSolid,
  PlusIcon as PlusSolid,
  PrinterIcon as PrinterSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleSolid,
  ShieldCheckIcon as ShieldCheckSolid,
  SparklesIcon as SparklesSolid,
  Squares2X2Icon as Squares2X2Solid,
  SunIcon as SunSolid,
  TrashIcon as TrashSolid,
  TrophyIcon as TrophySolid,
  UserGroupIcon as UserGroupSolid,
  UserIcon as UserSolid,
  UserPlusIcon as UserPlusSolid,
  VideoCameraIcon as VideoCameraSolid,
  XMarkIcon as XMarkSolid,
} from "@heroicons/react/24/solid";

type HeroIcon = ComponentType<SVGProps<SVGSVGElement>>;

const ICONS: Record<string, [HeroIcon, HeroIcon]> = {
  add: [PlusOutline, PlusSolid],
  add_box: [PlusCircleOutline, PlusCircleSolid],
  arrow_forward: [ArrowRightOutline, ArrowRightSolid],
  assignment: [ClipboardDocumentListOutline, ClipboardDocumentListSolid],
  assignment_turned_in: [ClipboardDocumentCheckOutline, ClipboardDocumentCheckSolid],
  bookmark_added: [BookmarkOutline, BookmarkSolid],
  calendar_month: [CalendarDaysOutline, CalendarDaysSolid],
  celebration: [SparklesOutline, SparklesSolid],
  chat: [ChatBubbleLeftRightOutline, ChatBubbleLeftRightSolid],
  check: [CheckOutline, CheckSolid],
  check_circle: [CheckCircleOutline, CheckCircleSolid],
  chevron_right: [ChevronRightOutline, ChevronRightSolid],
  close: [XMarkOutline, XMarkSolid],
  computer: [ComputerDesktopOutline, ComputerDesktopSolid],
  contact_page: [IdentificationOutline, IdentificationSolid],
  contact_support: [LifebuoyOutline, LifebuoySolid],
  content_copy: [ClipboardDocumentOutline, ClipboardDocumentSolid],
  corporate_fare: [BuildingOffice2Outline, BuildingOffice2Solid],
  dashboard: [Squares2X2Outline, Squares2X2Solid],
  dark_mode: [MoonOutline, MoonSolid],
  delete: [TrashOutline, TrashSolid],
  description: [DocumentTextOutline, DocumentTextSolid],
  devices: [DeviceTabletOutline, DeviceTabletSolid],
  download: [ArrowDownTrayOutline, ArrowDownTraySolid],
  draft: [DocumentOutline, DocumentSolid],
  error: [ExclamationCircleOutline, ExclamationCircleSolid],
  event: [CalendarOutline, CalendarSolid],
  event_available: [CalendarDaysOutline, CalendarDaysSolid],
  flag: [FlagOutline, FlagSolid],
  folder_open: [FolderOpenOutline, FolderOpenSolid],
  folder_zip: [FolderOutline, FolderSolid],
  forum: [ChatBubbleLeftRightOutline, ChatBubbleLeftRightSolid],
  group: [UserGroupOutline, UserGroupSolid],
  group_add: [UserPlusOutline, UserPlusSolid],
  handshake: [HandRaisedOutline, HandRaisedSolid],
  help: [QuestionMarkCircleOutline, QuestionMarkCircleSolid],
  history: [ClockOutline, ClockSolid],
  home: [HomeOutline, HomeSolid],
  inbox: [InboxOutline, InboxSolid],
  info: [InformationCircleOutline, InformationCircleSolid],
  inventory_2: [ArchiveBoxOutline, ArchiveBoxSolid],
  link: [LinkOutline, LinkSolid],
  light_mode: [SunOutline, SunSolid],
  location_on: [MapPinOutline, MapPinSolid],
  lock: [LockClosedOutline, LockClosedSolid],
  lock_reset: [KeyOutline, KeySolid],
  logout: [ArrowRightStartOnRectangleOutline, ArrowRightStartOnRectangleSolid],
  mail: [EnvelopeOutline, EnvelopeSolid],
  mark_email_unread: [EnvelopeOpenOutline, EnvelopeOpenSolid],
  menu: [Bars3Outline, Bars3Solid],
  notifications: [BellOutline, BellSolid],
  password: [KeyOutline, KeySolid],
  payments: [BanknotesOutline, BanknotesSolid],
  person: [UserOutline, UserSolid],
  phone: [PhoneOutline, PhoneSolid],
  post_add: [DocumentPlusOutline, DocumentPlusSolid],
  print: [PrinterOutline, PrinterSolid],
  priority_high: [ExclamationTriangleOutline, ExclamationTriangleSolid],
  radio_button_checked: [CheckCircleOutline, CheckCircleSolid],
  save: [ArrowDownOnSquareOutline, ArrowDownOnSquareSolid],
  search: [MagnifyingGlassOutline, MagnifyingGlassSolid],
  send: [PaperAirplaneOutline, PaperAirplaneSolid],
  settings: [Cog6ToothOutline, Cog6ToothSolid],
  smartphone: [DevicePhoneMobileOutline, DevicePhoneMobileSolid],
  sticky_note_2: [PencilSquareOutline, PencilSquareSolid],
  sync: [ArrowPathOutline, ArrowPathSolid],
  trending_up: [ArrowTrendingUpOutline, ArrowTrendingUpSolid],
  upload_file: [ArrowUpTrayOutline, ArrowUpTraySolid],
  verified: [ShieldCheckOutline, ShieldCheckSolid],
  video_camera_front: [VideoCameraOutline, VideoCameraSolid],
  videocam: [VideoCameraOutline, VideoCameraSolid],
  visibility: [EyeOutline, EyeSolid],
  visibility_off: [EyeSlashOutline, EyeSlashSolid],
  warning: [ExclamationTriangleOutline, ExclamationTriangleSolid],
  work: [BriefcaseOutline, BriefcaseSolid],
  workspace_premium: [TrophyOutline, TrophySolid],
};

type IconProps = {
  name: string;
  className?: string;
  filled?: boolean;
  size?: number;
  label?: string;
};

export function Icon({
  name,
  className = "",
  filled = false,
  size = 24,
  label,
}: IconProps) {
  const pair = ICONS[name] ?? [QuestionMarkCircleOutline, QuestionMarkCircleSolid];
  const Cmp = filled ? pair[1] : pair[0];

  return (
    <Cmp
      aria-hidden={label ? undefined : true}
      aria-label={label}
      className={`shrink-0 ${className}`}
      role={label ? "img" : undefined}
      style={{ width: size, height: size }}
    />
  );
}
