import type { Applicant, JobApplication, Recruiter } from "./types";

export const currentApplicantId = "app-alex";
export const currentRecruiterId = "rec-alex";

export const recruiters: Recruiter[] = [
  {
    id: "rec-alex",
    recruiterCode: "ABC-123",
    name: "Alex Rivers",
    preferredName: "Alex",
    email: "a.rivers@jobtrackerhub.com",
    phone: "+1 (555) 019-2834",
    phoneExt: "2041",
    location: "Chicago, IL (Hybrid)",
    title: "Senior Technical Recruiter",
    organization: "Job Tracker Hub",
    organizationAddress: "233 S Wacker Dr, Chicago, IL 60606",
    organizationWebsite: "https://jobtrackerhub.com",
    initials: "AR",
    applicantsManaged: 42,
  },
  {
    id: "rec-sarah",
    recruiterCode: "REC-2024-89XQ",
    name: "Sarah Jenkins",
    preferredName: "Sarah",
    email: "s.jenkins@jobtrackerhub.com",
    phone: "+1 (555) 019-2834",
    location: "Chicago, IL (Hybrid)",
    title: "Senior Talent Acquisition Specialist",
    organization: "Job Tracker Hub",
    organizationAddress: "233 S Wacker Dr, Chicago, IL 60606",
    organizationWebsite: "https://jobtrackerhub.com",
    initials: "SJ",
    applicantsManaged: 1284,
  },
];

export const applicants: Applicant[] = [
  {
    id: "app-alex",
    name: "Alex Johnson",
    email: "alex.j@example.com",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    title: "Software Engineer Applicant",
    experienceYears: 6,
    salaryExpectation: "$140k - $160k",
    fitScore: 88,
    recruiterId: "rec-sarah",
    initials: "AJ",
    joined: "Oct 2023",
    openToRelocation: true,
    remotePreferred: false,
  },
  {
    id: "app-sarah",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@example.com",
    phone: "(555) 123-4567",
    location: "Seattle, WA (Remote)",
    title: "Senior Product Designer",
    experienceYears: 8,
    salaryExpectation: "$140k - $160k",
    fitScore: 92,
    recruiterId: "rec-alex",
    initials: "SJ",
    joined: "Jan 2024",
    openToRelocation: false,
    remotePreferred: true,
  },
  {
    id: "app-david",
    name: "David Chen",
    email: "david.chen@example.com",
    phone: "(555) 222-1098",
    location: "Austin, TX",
    title: "Frontend Developer",
    experienceYears: 5,
    salaryExpectation: "$120k - $140k",
    fitScore: 81,
    recruiterId: "rec-alex",
    initials: "DC",
    joined: "Mar 2024",
    openToRelocation: true,
    remotePreferred: true,
  },
  {
    id: "app-marcus",
    name: "Marcus Johnson",
    email: "marcus.j@example.com",
    phone: "(555) 333-4411",
    location: "New York, NY",
    title: "Product Manager",
    experienceYears: 7,
    salaryExpectation: "$150k - $170k",
    fitScore: 76,
    recruiterId: "rec-alex",
    initials: "MJ",
    joined: "Feb 2024",
    openToRelocation: false,
    remotePreferred: false,
  },
  {
    id: "app-elena",
    name: "Elena Rodriguez",
    email: "elena.r@example.com",
    phone: "(555) 444-7788",
    location: "Austin, TX (Open to Relocation)",
    title: "Senior UX Designer",
    experienceYears: 9,
    salaryExpectation: "$130k - $150k",
    fitScore: 90,
    recruiterId: "rec-alex",
    initials: "ER",
    joined: "Nov 2023",
    openToRelocation: true,
    remotePreferred: false,
  },
  {
    id: "app-aisha",
    name: "Aisha Patel",
    email: "aisha.p@example.com",
    phone: "(555) 555-0101",
    location: "Remote",
    title: "Product Manager",
    experienceYears: 4,
    salaryExpectation: "$125k - $145k",
    fitScore: 84,
    recruiterId: "rec-alex",
    initials: "AP",
    joined: "Apr 2024",
    openToRelocation: false,
    remotePreferred: true,
  },
];

export const applications: JobApplication[] = [
  {
    id: "job-1",
    dateApplied: "2024-10-16",
    organization: "TechCorp Inc.",
    location: "San Francisco, CA (Hybrid)",
    phone: "(555) 010-2000",
    contactName: "Jordan Hale",
    contactEmail: "jordan.hale@techcorp.com",
    position: "Senior Frontend Engineer",
    notes: "Prepare system design examples around design systems.",
    status: "interview",
    postingUrl: "https://techcorp.example.com/careers/frontend",
    source: "jobBoard",
    applicantId: "app-alex",
    nextAction: "Prepare for interview",
    documents: [
      {
        id: "doc-1",
        kind: "resume",
        name: "Alex_Resume_ProductDesign_2024.pdf",
        sizeLabel: "1.2 MB",
        uploadedAt: "Oct 16, 2024",
      },
    ],
    comments: [],
    timeline: [
      {
        id: "t1",
        title: "Interview",
        description: "Technical round with hiring manager.",
        timestamp: "2 days ago",
        icon: "event",
        tone: "primary",
      },
      {
        id: "t2",
        title: "Application Viewed",
        description: "TechCorp Inc. reviewed your materials.",
        timestamp: "Yesterday",
        icon: "visibility",
        tone: "neutral",
      },
    ],
  },
  {
    id: "job-2",
    dateApplied: "2024-10-13",
    organization: "Creative Solutions",
    location: "Remote",
    phone: "(555) 010-3000",
    contactName: "Priya Shah",
    contactEmail: "priya@creativesolutions.com",
    position: "Product Designer",
    notes: "Assessment due this week.",
    status: "assessment",
    postingUrl: "https://creativesolutions.example.com/jobs/designer",
    source: "jobBoard",
    applicantId: "app-alex",
    nextAction: "Start assessment",
    documents: [
      {
        id: "doc-2",
        kind: "resume",
        name: "Alex_Resume_ProductDesign_2024.pdf",
        sizeLabel: "1.2 MB",
        uploadedAt: "Oct 13, 2024",
      },
      {
        id: "doc-3",
        kind: "coverLetter",
        name: "Cover_Letter_KT.docx",
        sizeLabel: "450 KB",
        uploadedAt: "Oct 13, 2024",
      },
    ],
    comments: [],
    timeline: [
      {
        id: "t3",
        title: "Assessment",
        description: "Portfolio exercise assigned.",
        timestamp: "5 days ago",
        icon: "assignment",
        tone: "secondary",
      },
    ],
  },
  {
    id: "job-3",
    dateApplied: "2024-10-09",
    organization: "DataSys Ltd",
    location: "New York, NY",
    phone: "(555) 010-4000",
    contactName: "Chris Nguyen",
    contactEmail: "chris.n@datasys.com",
    position: "Backend Developer",
    notes: "",
    status: "applied",
    postingUrl: "https://datasys.example.com/careers/backend",
    source: "jobBoard",
    applicantId: "app-alex",
    nextAction: "View details",
    documents: [],
    comments: [],
    timeline: [
      {
        id: "t4",
        title: "Application Submitted",
        description: "Waiting for recruiter review.",
        timestamp: "1 week ago",
        icon: "mail",
        tone: "neutral",
      },
    ],
  },
  {
    id: "job-4",
    dateApplied: "2024-09-02",
    organization: "Global Logistics",
    location: "Chicago, IL",
    phone: "(555) 010-5000",
    contactName: "Mina Park",
    contactEmail: "mina.park@globallogistics.com",
    position: "Operations Analyst",
    notes: "Offer received — review compensation details.",
    status: "offer",
    postingUrl: "https://globallogistics.example.com/jobs/ops",
    source: "referral",
    applicantId: "app-alex",
    nextAction: "Review offer",
    documents: [],
    comments: [],
    timeline: [
      {
        id: "t5",
        title: "Offer Received",
        description: "Compensation package uploaded.",
        timestamp: "2 hrs ago",
        icon: "workspace_premium",
        tone: "success",
      },
    ],
  },
  {
    id: "job-5",
    dateApplied: "2024-06-18",
    organization: "Quantify Data",
    location: "Remote",
    phone: "(555) 010-6000",
    contactName: "Lee Ortiz",
    contactEmail: "lee@quantify.com",
    position: "Data Analyst",
    notes: "Closed out after final round.",
    status: "archived",
    postingUrl: "https://quantify.example.com/jobs/analyst",
    source: "companySite",
    applicantId: "app-alex",
    documents: [],
    comments: [],
    timeline: [],
  },
  {
    id: "job-sj-1",
    dateApplied: "2024-10-12",
    organization: "Job Tracker Hub Partners",
    location: "Seattle, WA (Remote)",
    phone: "(555) 200-1000",
    contactName: "Jason Davis",
    contactEmail: "jason.davis@jobtrackerhub.com",
    position: "Senior UX Researcher - Platform Team",
    notes: "Strong case study on enterprise dashboards.",
    status: "interview",
    postingUrl: "https://jobtrackerhub.example.com/jobs/uxr",
    source: "jobBoard",
    applicantId: "app-sarah",
    nextAction: "Technical Portfolio Review",
    documents: [
      {
        id: "doc-sj-1",
        kind: "resume",
        name: "SJenkins_Resume_2024.pdf",
        sizeLabel: "2.4 MB",
        uploadedAt: "Oct 12, 2024",
      },
      {
        id: "doc-sj-2",
        kind: "coverLetter",
        name: "Cover_Letter_KT.docx",
        sizeLabel: "450 KB",
        uploadedAt: "Oct 12, 2024",
      },
    ],
    comments: [
      {
        id: "n-sj-1",
        author: "Jason Davis",
        authorInitials: "JD",
        createdAt: "Today, 10:30 AM",
        body: "Sarah presented an incredibly thorough case study on enterprise dashboard redesigns. Very strong structural thinking.",
      },
    ],
    timeline: [
      {
        id: "sj-t1",
        title: "Technical Interview Completed",
        description: "Conducted with Jason Davis. Feedback pending but initial signs are very positive.",
        timestamp: "Today, 10:30 AM",
        icon: "videocam",
        tone: "primary",
      },
      {
        id: "sj-t2",
        title: "Preparation Email Sent",
        description: "Sent Sarah the technical interview prep guide and portfolio requirements.",
        timestamp: "Yesterday, 2:15 PM",
        icon: "mail",
        tone: "neutral",
      },
      {
        id: "sj-t3",
        title: "Recruiter Screen Passed",
        description: "Great communication skills. Salary expectations align. Moved to next stage.",
        timestamp: "Oct 15, 2024",
        icon: "assignment_turned_in",
        tone: "success",
      },
      {
        id: "sj-t4",
        title: "Application Received",
        description: "Applied via direct career site link.",
        timestamp: "Oct 12, 2024",
        icon: "description",
        tone: "neutral",
      },
    ],
  },
  {
    id: "job-er-1",
    dateApplied: "2023-10-12",
    organization: "Job Tracker Hub",
    location: "Austin, TX",
    phone: "(555) 200-2000",
    contactName: "Mark S.",
    contactEmail: "mark.s@jobtrackerhub.com",
    position: "Senior UX Designer",
    notes: "Pending review of submitted portfolio exercise.",
    status: "assessment",
    postingUrl: "https://jobtrackerhub.example.com/jobs/ux",
    source: "jobBoard",
    applicantId: "app-elena",
    nextAction: "Review files",
    documents: [
      {
        id: "doc-er-1",
        kind: "resume",
        name: "E_Rodriguez_Resume.pdf",
        sizeLabel: "1.2 MB",
        uploadedAt: "Oct 12, 2023",
      },
      {
        id: "doc-er-2",
        kind: "coverLetter",
        name: "Cover_Letter_KT.docx",
        sizeLabel: "450 KB",
        uploadedAt: "Oct 12, 2023",
      },
      {
        id: "doc-er-3",
        kind: "other",
        name: "design_exercise_final.zip",
        sizeLabel: "14 MB",
        uploadedAt: "Oct 24, 2023",
      },
    ],
    comments: [
      {
        id: "n-er-1",
        author: "Sarah L. (Design Lead)",
        authorInitials: "SL",
        createdAt: "Oct 21",
        body: "Reviewed portfolio. Very strong visual design skills. Make sure we ask about her process for handling conflicting stakeholder feedback during the technical review.",
      },
      {
        id: "n-er-2",
        author: "Mark S. (Recruiter)",
        authorInitials: "MS",
        createdAt: "Oct 20, 2023",
        body: "Strong communication skills. Experience aligns perfectly with the requirements for the mobile app redesign project. Advancing to technical assessment.",
      },
    ],
    timeline: [
      {
        id: "er-t1",
        title: "Technical Assessment",
        description: "Pending review of submitted portfolio exercise.",
        timestamp: "Current Stage",
        icon: "sync",
        tone: "primary",
      },
      {
        id: "er-t2",
        title: "Screening Interview",
        description: "30-minute introductory call with Hiring Manager.",
        timestamp: "Oct 20, 2023 • 2:00 PM",
        icon: "check",
        tone: "neutral",
        note: {
          id: "n-er-2",
          author: "Mark S. (Recruiter)",
          authorInitials: "MS",
          createdAt: "Oct 20, 2023",
          body: "Strong communication skills. Experience aligns perfectly with the requirements for the mobile app redesign project. Advancing to technical assessment.",
        },
      },
      {
        id: "er-t3",
        title: "Application Submitted",
        description: "Applied via direct career site link.",
        timestamp: "Oct 12, 2023",
        icon: "mail",
        tone: "neutral",
      },
    ],
  },
  {
    id: "job-dc-1",
    dateApplied: "2024-10-20",
    organization: "Northwind Labs",
    location: "Austin, TX",
    phone: "(555) 200-3000",
    contactName: "Alex Rivers",
    contactEmail: "a.rivers@jobtrackerhub.com",
    position: "Frontend Developer",
    notes: "Needs coaching follow-up before onsite.",
    status: "screening",
    postingUrl: "https://northwind.example.com/jobs/fe",
    source: "jobBoard",
    applicantId: "app-david",
    documents: [],
    comments: [],
    timeline: [
      {
        id: "dc-t1",
        title: "Tech screen scheduled",
        description: "Interview booked for this week.",
        timestamp: "2 hours ago",
        icon: "event",
        tone: "primary",
      },
    ],
  },
  {
    id: "job-mj-1",
    dateApplied: "2024-10-08",
    organization: "Horizon Apps",
    location: "New York, NY",
    phone: "(555) 200-4000",
    contactName: "Alex Rivers",
    contactEmail: "a.rivers@jobtrackerhub.com",
    position: "Product Manager",
    notes: "",
    status: "applied",
    postingUrl: "https://horizon.example.com/jobs/pm",
    source: "referral",
    applicantId: "app-marcus",
    documents: [],
    comments: [],
    timeline: [],
  },
  {
    id: "job-ap-1",
    dateApplied: "2024-10-17",
    organization: "Brightline",
    location: "Remote",
    phone: "(555) 200-5000",
    contactName: "Alex Rivers",
    contactEmail: "a.rivers@jobtrackerhub.com",
    position: "Product Manager",
    notes: "",
    status: "applied",
    postingUrl: "https://brightline.example.com/jobs/pm",
    source: "recruiter",
    applicantId: "app-aisha",
    documents: [],
    comments: [],
    timeline: [
      {
        id: "ap-t1",
        title: "Application Received",
        description: "New application from Aisha Patel for Product Manager.",
        timestamp: "Yesterday",
        icon: "description",
        tone: "neutral",
      },
    ],
  },
];

export function getApplicant(id: string) {
  return applicants.find((item) => item.id === id);
}

export function getRecruiter(id: string) {
  return recruiters.find((item) => item.id === id);
}

export function applicationsForApplicant(applicantId: string) {
  return applications.filter((item) => item.applicantId === applicantId);
}

export function applicationsForRecruiter(recruiterId: string) {
  const ids = applicants
    .filter((item) => item.recruiterId === recruiterId)
    .map((item) => item.id);
  return applications.filter((item) => ids.includes(item.applicantId));
}

export function getApplication(id: string) {
  return applications.find((item) => item.id === id);
}

export const currentApplicant = applicants[0];
export const currentRecruiter = recruiters[0];
export const assignedRecruiter = recruiters[1];